CREATE TABLE `employees`(
    `id` BIGINT (20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(50) NOT NULL,
    `email` VARCHAR(50) NULL,
    `salary` BIGINT(20) UNSIGNED,
    `designation` VARCHAR(200) NOT NULL
)

INSERT INTO `employees` (`name`, `email`, `salary`, `designation`) VALUES
('Alice Johnson', 'alice.johnson@example.com', 60000, 'Software Engineer'),
('Bob Smith', 'bob.smith@example.com', 75000, 'Project Manager'),
('Charlie Davis', NULL, 50000, 'Junior Developer'),
('Diana Roberts', 'diana.roberts@example.com', 80000, 'Senior Analyst'),
('Ethan Brown', 'ethan.brown@example.com', 45000, 'Quality Assurance Engineer'),
('Fiona Green', 'fiona.green@example.com', 70000, 'Product Manager'),
('George White', 'george.white@example.com', 65000, 'Database Administrator'),
('Hannah Hall', NULL, 48000, 'Technical Support Specialist'),
('Isaac Lee', 'isaac.lee@example.com', 55000, 'Frontend Developer'),
('Jack Wilson', 'jack.wilson@example.com', 72000, 'DevOps Engineer'),
('Karen Adams', 'karen.adams@example.com', 78000, 'UX Designer'),
('Liam Harris', 'liam.harris@example.com', 67000, 'Cloud Architect'),
('Mia Clark', 'mia.clark@example.com', 50000, 'Content Strategist'),
('Noah Lewis', NULL, 62000, 'Data Scientist'),
('Olivia Young', 'olivia.young@example.com', 88000, 'IT Consultant'),
('Paul King', 'paul.king@example.com', 54000, 'Network Engineer'),
('Quincy Scott', 'quincy.scott@example.com', 46000, 'Help Desk Technician'),
('Rachel Turner', 'rachel.turner@example.com', 73000, 'Cybersecurity Analyst'),
('Sophia Hill', 'sophia.hill@example.com', 78000, 'Marketing Manager'),
('Thomas Baker', NULL, 52000, 'Mobile App Developer'),
('Ursula Gray', 'ursula.gray@example.com', 65000, 'SEO Specialist'),
('Victor Reed', 'victor.reed@example.com', 56000, 'System Administrator'),
('Willow Kelly', 'willow.kelly@example.com', 47000, 'Social Media Manager'),
('Xander Parker', 'xander.parker@example.com', 85000, 'AI Researcher'),
('Yara Collins', NULL, 69000, 'Data Engineer'),
('Zachary Hughes', 'zachary.hughes@example.com', 75000, 'Full Stack Developer'),
('Ava Mitchell', 'ava.mitchell@example.com', 68000, 'HR Specialist'),
('Benjamin Perez', NULL, 62000, 'Operations Manager'),
('Chloe Ross', 'chloe.ross@example.com', 72000, 'Solutions Architect'),
('Daniel Sanders', 'daniel.sanders@example.com', 54000, 'Tech Support Engineer');
