SELECT CHAR_LENGTH("Hello World") AS COL 

SELECT LOWER ("Hello World") AS COl

SELECT  UPPER ("Hello World") AS COl

SELECT TRIM("Hello world") AS COl

SELECT RTRIM("Hello world") AS COl

SELECT LTRIM("Hello world") AS COl

SELECT REVERSE ("HELLO") AS COL

SELECT FORMAT(1234567.89,2)AS COL

SELECT CONCAT ('HELLO','','SQL') AS COL

SELECT REPLACE('HELLO WORLD','WORLD','DUNIYA') AS COL

